name: Publish in GitHub Package Registry

on:
  push: main

jobs:

  on-push-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: It ran because of the commit to push
        run: |
          echo "It ran because of the commit to push"
          
  publish-gpr:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node.js Version
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Show Triggered Tag
        run: |
          echo "Triggered tag: ${{ github.ref }}"
      
      - name: Show Commit Details
        run: |
          git log -1 --pretty=format:"Commit by %an <%ae>%n%n%s%n%n%b"

      - name: Install dependencies
        run: npm install

      - name: Build package files
        run: npm run build
