name: Publish in GitHub Package Registry

on:
  push: main

jobs:


  publish-gpr:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set Node.js Version
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Show Triggered Tag
        run: echo "Triggered tag: ${{ github.ref }}"
      
      - name: Show Commit Details
        run: |
          git log -1 --pretty=format:"Commit by %an <%ae>%n%n%s%n%n%b"

      - name: Install dependencies
        run: npm install

      - name: Build package files
        run: npm run build

